### ISSUE TITLE
Test with Magento 2.4 & PHP 7.4

### ISSUE THREAD

**Issue by scottsb** [ripenecommerce/magento2-postmark#5]

**Comment by erfanimani** [comment]
Hi @scottsb, thanks for this module! Were there any updates on this one?

**Comment by scottsb** [comment]
@erfanimani No, we do not have any clients running on Magento 2.4 yet, so we have not tested this there. If anyone else has the opportunity to try it out and report back, that would be useful.

**Comment by jaywilliams** [comment]
If you're wanting to use this extension on Magento 2.4 & PHP 7.4, give pull request #12 a spin.

**Comment by palakaccorin** [comment]
@scottsb I am trying to install this module in Magento 2.4.3 and PHP 7.4 using composer and I am facing a compatibility issue. and PR #12  is already open for that issue. so when you are planning to merge it?
